name = "SelfOrganizingMaps"
uuid = "ba4b7379-301a-4be0-bee6-171e4e152787"
authors = ["John Waczak <john.louis.waczak@gmail.com>"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Distances = "0.10"
julia = "1.8"
